backend:
  name: github
  repo: manasp21/poetry_website
  branch: main # Replace with your default branch if not main

media_folder: "assets/images/poems" # Folder where uploaded media will be stored
public_folder: "/assets/images/poems" # Folder where media will be served from

collections:
  - name: "poems" # A friendly name for the collection
    label: "Poems" # The label displayed in the UI
    folder: "Poetry/by_language/english/lengths/short" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., "my-new-poem.md"
    fields: # The fields for each document, corresponding to the front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Language", name: "language", widget: "string", default: "english"}
      - {label: "Form", name: "form", widget: "string", default: "short"}
      - {label: "Length", name: "length", widget: "string", default: "short"}